env: "local" # local, dev, prod

api:
  addr: :8080
  writeTimeout: 15s
  name: SkillsRockTodoList

postgreSql:
 host: localhost
 port: 5433
 name: postgres
 user: postgres
 password: postgres
 sslMode: disable
 poolMaxConns: 10
 poolMaxConnLifeTime: 300s
 poolMaxConnIidleTime: 150s